executableModuleName=CyclingPower_Web-application-gwt
executableModuleVersion=1.0.0-SNAPSHOT
applicationModuleName=CyclingPower_Web-application
pwa=null
mavenBuildTimestamp=2026-03-21T15:01:00Z
environment=development